<?xml version="1.0" encoding="utf-8"?><Database Name="ProjectMVC" Class="CompanyDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-TTHPNUF7;Initial Catalog=ProjectMVC;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ProjectMVCConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Total" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AccountType" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Deal" Member="Deals">
    <Type Name="Deal">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CustomerEmail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DealDate" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
      <Column Name="FlowerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Flowers" Member="Flowers">
    <Type Name="Flower">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FlowerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ImagePath" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Price" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_Account_Loginuser_Check" Method="sp_Account_Loginuser_Check">
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="PassWord" Parameter="passWord" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="res" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Check_Account" Method="sp_Check_Account">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="res" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Create_Account_Admin" Method="sp_Create_Account_Admin">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Create_Account_Main" Method="sp_Create_Account_Main">
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="FirstName" Parameter="firstName" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="LastName" Parameter="lastName" Type="System.String" DbType="NVarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Account_Login_Check" Method="sp_Account_Login_Check">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="PassWord" Parameter="passWord" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="res" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>